#ifndef __OBLIVIRA_UNTRUSTED_CONFIG_HH__
#define __OBLIVIRA_UNTRUSTED_CONFIG_HH__

#define NUM_DID_REQ_THR 4
#define NUM_DOC_FETCH_THR 4

#define MAX_PATH_LEN FILENAME_MAX
#define MAX_EVENTS 2000

#define DID_REQ_PORT 4433
#define DOC_FETCH_PORT 8081

#define DRF_MAX_LEN 2048

#endif
